#!/usr/bin/env python3
import sys
import os

script = os.path.join(os.path.dirname(os.path.realpath(__file__)), "kore.py")
if os.path.exists(script):
    os.execvp("python3", ["python3", script] + sys.argv[1:])
else:
    print(f"Error: kore.py not found at {script}")
    sys.exit(1)
